name: Update Notion Database

on:
  workflow_dispatch:
  schedule:
    # - cron: '0 8 * * *'  # Run every day at 8am UTC

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install python-dotenv
          pip install -r requirements.txt

      - name: Run notion update script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          STORYGRAPH_EMAIL: ${{ secrets.STORYGRAPH_EMAIL }}
          STORYGRAPH_PASSWORD: ${{ secrets.STORYGRAPH_PASSWORD }}
        run: |
          echo "Starting Notion update script..."
          python notion_update.py
          echo "Notion update script completed."
